---
- name: Install Nginx, npm, create Virtual Hosts, Install SSL, and builds Polymer
  hosts: webservers
  become: yes
  become_user: root
  vars:
    update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{env}}.yml

  roles:
    - nginx
    - certbot
    - appserver
